name: 📂 | Build Documents

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 💥 | Checkout
        uses: actions/checkout@v2

      - name: 🚀 | Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: 🛠 | Generating
        uses: andstor/jsdoc-action@v1
        with:
          config_file: jsdoc.json

      - name: 👀 | Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: 🔴 | Publish Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: docs/irpayments/${{ steps.package-version.outputs.current-version }}/

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 💥 | Checkout
      - uses: actions/checkout@v1

      - name: 🚀 | Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install

      - name: 🎉 | Publish Package
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}